name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Absterrg0/mini-project/sdk@main
        env:
          EXECFORGE_API_TOKEN: ${{ secrets.EXECFORGE_API_TOKEN }}
          EXECFORGE_API_URL: ${{ secrets.EXECFORGE_API_URL }}  # leave blank in prod, set to http://localhost:3000 for local

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build & test
        run: npm run build && npm test
